name: imc_body
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_modular: ^5.0.3
  flutter_native_splash: ^2.2.3+1
  flutter_launcher_icons: ^0.9.3


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/splash.png"
  android: true
  ios: true

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon.png"
  remove_alpha_ios: true


flutter:
  assets:
    - assets/icon.png
    - assets/splash.png


  uses-material-design: true